#URL: https://rutracker.net/forum/viewforum.php?f=252

URL: https://www.ebay.com/b/Apple-Cell-Phone-Cases-and-Covers/20349/bn_319677

ParserType: lxml
HEADERS: "({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0', 'Accept-Language': 'en-US'})"